---
 -  
    hosts: all
    name: 'install prequistes for elearning project'
    become: true
    roles:
        - stack
        #- {stack, db_name: mydb, db_user_name: user, db_user_password: pass}   passing variables here will override defaults
        





